name: TikTok Trending Videos Scraper

on:
  schedule:
    - cron: '0 0 * * 1'  # Esegui ogni lunedì a mezzanotte
  workflow_dispatch:      # Permette l'esecuzione manuale

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            playwright-${{ runner.os }}-
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium --with-deps
          
      - name: Execute scraper
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          echo "Starting script execution..."
          python -u run.py  # -u forza l'output unbuffered
        
      - name: Check generated files
        if: always()  # Esegui questo step anche se il precedente fallisce
        run: |
          echo "Checking for generated files..."
          ls -la
          if [ -f "tiktok_trending.html" ]; then
            echo "HTML file was generated"
            du -h tiktok_trending.html
          else
            echo "HTML file was not generated"
          fi
          
      - name: Commit and push if changed
        if: success()  # Solo se tutto è andato bene
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update TikTok trending videos" --allow-empty)
          
      - name: Push changes
        if: success()  # Solo se tutto è andato bene
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
